const swaggerAutogen = require('swagger-autogen')()

const swaggerOutputFile = './swagger_output.json'
const swaggerEndpointFile = ['./src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My Blog RESTAPI",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
}
swaggerAutogen(swaggerOutputFile, swaggerEndpointFile,doc)